runtime: php55
api_version: 1
service: bingsearch

##comment here

handlers:
 - url: /.*
   script: main.php
   secure: always

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.mdown$
  - ^(.*/)?.*\.dist$
  - ^(.*/)?.*\.xml$
  - ^(.*/)?.*LICENSE$
  - ^(.*/)?.*/examples/.*$
  - ^(.*/)?.*/phpunit/.*$
  - ^(.*/)?.*/[Tt]ests/.*$
  - secrets/


